on:
  rss01:
    url: https://80.lv/feed/
  rss02:
    url: https://www.theverge.com/rss/index.xml
jobs:
  request01:
    name: Request01
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'rss01' }}
    steps:
      - name: Request01
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.CUBOX_API }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "description":"${{on.rss.outputs.contentSnippet}}",
              "folder":"80 Level"
            }
  request02:
    name: Request02
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'rss02' }}
    steps:
      - name: Request02
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.CUBOX_API }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "description":"${{on.rss.outputs.contentSnippet}}",
              "folder":"The Verge"
            }
